name: Merge-Tests
on:
  push:
    branches: [ main ]

env:
  KEY_HEADER: "X-API-KEY: ${{ secrets.API_KEY }}"
  PAYLOAD: "{ \"gitHub\": { \"owner\": \"${{github.repository_owner}}\", \"repo\": \"${{github.event.repository.name}}\", \"sha\": \"${{ github.event.pull_request.head.sha }}\" } }"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run GitHub Automation Test Suite
        run: curl
             -X POST
             -H "$KEY_HEADER"
             -d "$PAYLOAD"
             -s
             https://api.reflect.run/v1/suites/github-automation-test-suite/executions
      - name: Run Sunrise/Sunset Data Driven Test Suite
        run: curl
             -X POST
             -H "$KEY_HEADER"
             -d "$PAYLOAD"
             -s
             https://api.reflect.run/v1/suites/data-driven-test-suite-sunrisesunset/executions